# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/hidden.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import google.protobuf.descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/proto/hidden.proto',
  package='boa.types',
  serialized_pb='\n\x16src/proto/hidden.proto\x12\tboa.types\x1a google/protobuf/descriptor.proto:/\n\x06hidden\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x08:.\n\x05\x61lias\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\t:4\n\tkind_func\x12\x1f.google.protobuf.MessageOptions\x18\xd1\x86\x03 \x01(\t')


HIDDEN_FIELD_NUMBER = 50000
hidden = _descriptor.FieldDescriptor(
  name='hidden', full_name='boa.types.hidden', index=0,
  number=50000, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
ALIAS_FIELD_NUMBER = 50002
alias = _descriptor.FieldDescriptor(
  name='alias', full_name='boa.types.alias', index=1,
  number=50002, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
KIND_FUNC_FIELD_NUMBER = 50001
kind_func = _descriptor.FieldDescriptor(
  name='kind_func', full_name='boa.types.kind_func', index=2,
  number=50001, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(hidden)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(alias)
google.protobuf.descriptor_pb2.MessageOptions.RegisterExtension(kind_func)

# @@protoc_insertion_point(module_scope)
