// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: output.proto

package boa.types;

public final class Output {
  private Output() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BoaResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .boa.types.ResultMap results = 1;
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    java.util.List<boa.types.Output.ResultMap> 
        getResultsList();
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    boa.types.Output.ResultMap getResults(int index);
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    int getResultsCount();
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    java.util.List<? extends boa.types.Output.ResultMapOrBuilder> 
        getResultsOrBuilderList();
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    boa.types.Output.ResultMapOrBuilder getResultsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code boa.types.BoaResult}
   */
  public static final class BoaResult extends
      com.google.protobuf.GeneratedMessage
      implements BoaResultOrBuilder {
    // Use BoaResult.newBuilder() to construct.
    private BoaResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BoaResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BoaResult defaultInstance;
    public static BoaResult getDefaultInstance() {
      return defaultInstance;
    }

    public BoaResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BoaResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                results_ = new java.util.ArrayList<boa.types.Output.ResultMap>();
                mutable_bitField0_ |= 0x00000001;
              }
              results_.add(input.readMessage(boa.types.Output.ResultMap.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return boa.types.Output.internal_static_boa_types_BoaResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return boa.types.Output.internal_static_boa_types_BoaResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              boa.types.Output.BoaResult.class, boa.types.Output.BoaResult.Builder.class);
    }

    public static com.google.protobuf.Parser<BoaResult> PARSER =
        new com.google.protobuf.AbstractParser<BoaResult>() {
      public BoaResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoaResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BoaResult> getParserForType() {
      return PARSER;
    }

    // repeated .boa.types.ResultMap results = 1;
    public static final int RESULTS_FIELD_NUMBER = 1;
    private java.util.List<boa.types.Output.ResultMap> results_;
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    public java.util.List<boa.types.Output.ResultMap> getResultsList() {
      return results_;
    }
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    public java.util.List<? extends boa.types.Output.ResultMapOrBuilder> 
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    public boa.types.Output.ResultMap getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated .boa.types.ResultMap results = 1;</code>
     */
    public boa.types.Output.ResultMapOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private void initFields() {
      results_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getResultsCount(); i++) {
        if (!getResults(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(1, results_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, results_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static boa.types.Output.BoaResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Output.BoaResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Output.BoaResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Output.BoaResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Output.BoaResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Output.BoaResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static boa.types.Output.BoaResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static boa.types.Output.BoaResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static boa.types.Output.BoaResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Output.BoaResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(boa.types.Output.BoaResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code boa.types.BoaResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements boa.types.Output.BoaResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return boa.types.Output.internal_static_boa_types_BoaResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return boa.types.Output.internal_static_boa_types_BoaResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                boa.types.Output.BoaResult.class, boa.types.Output.BoaResult.Builder.class);
      }

      // Construct using boa.types.Output.BoaResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return boa.types.Output.internal_static_boa_types_BoaResult_descriptor;
      }

      public boa.types.Output.BoaResult getDefaultInstanceForType() {
        return boa.types.Output.BoaResult.getDefaultInstance();
      }

      public boa.types.Output.BoaResult build() {
        boa.types.Output.BoaResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public boa.types.Output.BoaResult buildPartial() {
        boa.types.Output.BoaResult result = new boa.types.Output.BoaResult(this);
        int from_bitField0_ = bitField0_;
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof boa.types.Output.BoaResult) {
          return mergeFrom((boa.types.Output.BoaResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(boa.types.Output.BoaResult other) {
        if (other == boa.types.Output.BoaResult.getDefaultInstance()) return this;
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getResultsCount(); i++) {
          if (!getResults(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        boa.types.Output.BoaResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (boa.types.Output.BoaResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .boa.types.ResultMap results = 1;
      private java.util.List<boa.types.Output.ResultMap> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          results_ = new java.util.ArrayList<boa.types.Output.ResultMap>(results_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Output.ResultMap, boa.types.Output.ResultMap.Builder, boa.types.Output.ResultMapOrBuilder> resultsBuilder_;

      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public java.util.List<boa.types.Output.ResultMap> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public boa.types.Output.ResultMap getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public Builder setResults(
          int index, boa.types.Output.ResultMap value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public Builder setResults(
          int index, boa.types.Output.ResultMap.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public Builder addResults(boa.types.Output.ResultMap value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public Builder addResults(
          int index, boa.types.Output.ResultMap value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public Builder addResults(
          boa.types.Output.ResultMap.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public Builder addResults(
          int index, boa.types.Output.ResultMap.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends boa.types.Output.ResultMap> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          super.addAll(values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public boa.types.Output.ResultMap.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public boa.types.Output.ResultMapOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public java.util.List<? extends boa.types.Output.ResultMapOrBuilder> 
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public boa.types.Output.ResultMap.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            boa.types.Output.ResultMap.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public boa.types.Output.ResultMap.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, boa.types.Output.ResultMap.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.ResultMap results = 1;</code>
       */
      public java.util.List<boa.types.Output.ResultMap.Builder> 
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Output.ResultMap, boa.types.Output.ResultMap.Builder, boa.types.Output.ResultMapOrBuilder> 
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              boa.types.Output.ResultMap, boa.types.Output.ResultMap.Builder, boa.types.Output.ResultMapOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:boa.types.BoaResult)
    }

    static {
      defaultInstance = new BoaResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:boa.types.BoaResult)
  }

  public interface ResultMapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string key = 1;
    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // repeated string values = 2;
    /**
     * <code>repeated string values = 2;</code>
     */
    java.util.List<java.lang.String>
    getValuesList();
    /**
     * <code>repeated string values = 2;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated string values = 2;</code>
     */
    java.lang.String getValues(int index);
    /**
     * <code>repeated string values = 2;</code>
     */
    com.google.protobuf.ByteString
        getValuesBytes(int index);

    // repeated .boa.types.ResultMap keys = 3;
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    java.util.List<boa.types.Output.ResultMap> 
        getKeysList();
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    boa.types.Output.ResultMap getKeys(int index);
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    int getKeysCount();
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    java.util.List<? extends boa.types.Output.ResultMapOrBuilder> 
        getKeysOrBuilderList();
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    boa.types.Output.ResultMapOrBuilder getKeysOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code boa.types.ResultMap}
   */
  public static final class ResultMap extends
      com.google.protobuf.GeneratedMessage
      implements ResultMapOrBuilder {
    // Use ResultMap.newBuilder() to construct.
    private ResultMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResultMap(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResultMap defaultInstance;
    public static ResultMap getDefaultInstance() {
      return defaultInstance;
    }

    public ResultMap getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResultMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                values_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              values_.add(input.readBytes());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                keys_ = new java.util.ArrayList<boa.types.Output.ResultMap>();
                mutable_bitField0_ |= 0x00000004;
              }
              keys_.add(input.readMessage(boa.types.Output.ResultMap.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new com.google.protobuf.UnmodifiableLazyStringList(values_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          keys_ = java.util.Collections.unmodifiableList(keys_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return boa.types.Output.internal_static_boa_types_ResultMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return boa.types.Output.internal_static_boa_types_ResultMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              boa.types.Output.ResultMap.class, boa.types.Output.ResultMap.Builder.class);
    }

    public static com.google.protobuf.Parser<ResultMap> PARSER =
        new com.google.protobuf.AbstractParser<ResultMap>() {
      public ResultMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResultMap(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResultMap> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string values = 2;
    public static final int VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList values_;
    /**
     * <code>repeated string values = 2;</code>
     */
    public java.util.List<java.lang.String>
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }

    // repeated .boa.types.ResultMap keys = 3;
    public static final int KEYS_FIELD_NUMBER = 3;
    private java.util.List<boa.types.Output.ResultMap> keys_;
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    public java.util.List<boa.types.Output.ResultMap> getKeysList() {
      return keys_;
    }
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    public java.util.List<? extends boa.types.Output.ResultMapOrBuilder> 
        getKeysOrBuilderList() {
      return keys_;
    }
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    public int getKeysCount() {
      return keys_.size();
    }
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    public boa.types.Output.ResultMap getKeys(int index) {
      return keys_.get(index);
    }
    /**
     * <code>repeated .boa.types.ResultMap keys = 3;</code>
     */
    public boa.types.Output.ResultMapOrBuilder getKeysOrBuilder(
        int index) {
      return keys_.get(index);
    }

    private void initFields() {
      key_ = "";
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      keys_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getKeysCount(); i++) {
        if (!getKeys(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeBytes(2, values_.getByteString(i));
      }
      for (int i = 0; i < keys_.size(); i++) {
        output.writeMessage(3, keys_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(values_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      for (int i = 0; i < keys_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, keys_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static boa.types.Output.ResultMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Output.ResultMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Output.ResultMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Output.ResultMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Output.ResultMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Output.ResultMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static boa.types.Output.ResultMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static boa.types.Output.ResultMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static boa.types.Output.ResultMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Output.ResultMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(boa.types.Output.ResultMap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code boa.types.ResultMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements boa.types.Output.ResultMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return boa.types.Output.internal_static_boa_types_ResultMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return boa.types.Output.internal_static_boa_types_ResultMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                boa.types.Output.ResultMap.class, boa.types.Output.ResultMap.Builder.class);
      }

      // Construct using boa.types.Output.ResultMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKeysFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (keysBuilder_ == null) {
          keys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          keysBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return boa.types.Output.internal_static_boa_types_ResultMap_descriptor;
      }

      public boa.types.Output.ResultMap getDefaultInstanceForType() {
        return boa.types.Output.ResultMap.getDefaultInstance();
      }

      public boa.types.Output.ResultMap build() {
        boa.types.Output.ResultMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public boa.types.Output.ResultMap buildPartial() {
        boa.types.Output.ResultMap result = new boa.types.Output.ResultMap(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new com.google.protobuf.UnmodifiableLazyStringList(
              values_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.values_ = values_;
        if (keysBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            keys_ = java.util.Collections.unmodifiableList(keys_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.keys_ = keys_;
        } else {
          result.keys_ = keysBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof boa.types.Output.ResultMap) {
          return mergeFrom((boa.types.Output.ResultMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(boa.types.Output.ResultMap other) {
        if (other == boa.types.Output.ResultMap.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        if (keysBuilder_ == null) {
          if (!other.keys_.isEmpty()) {
            if (keys_.isEmpty()) {
              keys_ = other.keys_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureKeysIsMutable();
              keys_.addAll(other.keys_);
            }
            onChanged();
          }
        } else {
          if (!other.keys_.isEmpty()) {
            if (keysBuilder_.isEmpty()) {
              keysBuilder_.dispose();
              keysBuilder_ = null;
              keys_ = other.keys_;
              bitField0_ = (bitField0_ & ~0x00000004);
              keysBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKeysFieldBuilder() : null;
            } else {
              keysBuilder_.addAllMessages(other.keys_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        for (int i = 0; i < getKeysCount(); i++) {
          if (!getKeys(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        boa.types.Output.ResultMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (boa.types.Output.ResultMap) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // repeated string values = 2;
      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public java.util.List<java.lang.String>
          getValuesList() {
        return java.util.Collections.unmodifiableList(values_);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder setValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesIsMutable();
        super.addAll(values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }

      // repeated .boa.types.ResultMap keys = 3;
      private java.util.List<boa.types.Output.ResultMap> keys_ =
        java.util.Collections.emptyList();
      private void ensureKeysIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          keys_ = new java.util.ArrayList<boa.types.Output.ResultMap>(keys_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Output.ResultMap, boa.types.Output.ResultMap.Builder, boa.types.Output.ResultMapOrBuilder> keysBuilder_;

      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public java.util.List<boa.types.Output.ResultMap> getKeysList() {
        if (keysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(keys_);
        } else {
          return keysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public int getKeysCount() {
        if (keysBuilder_ == null) {
          return keys_.size();
        } else {
          return keysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public boa.types.Output.ResultMap getKeys(int index) {
        if (keysBuilder_ == null) {
          return keys_.get(index);
        } else {
          return keysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public Builder setKeys(
          int index, boa.types.Output.ResultMap value) {
        if (keysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeysIsMutable();
          keys_.set(index, value);
          onChanged();
        } else {
          keysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public Builder setKeys(
          int index, boa.types.Output.ResultMap.Builder builderForValue) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          keys_.set(index, builderForValue.build());
          onChanged();
        } else {
          keysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public Builder addKeys(boa.types.Output.ResultMap value) {
        if (keysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeysIsMutable();
          keys_.add(value);
          onChanged();
        } else {
          keysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public Builder addKeys(
          int index, boa.types.Output.ResultMap value) {
        if (keysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeysIsMutable();
          keys_.add(index, value);
          onChanged();
        } else {
          keysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public Builder addKeys(
          boa.types.Output.ResultMap.Builder builderForValue) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          keys_.add(builderForValue.build());
          onChanged();
        } else {
          keysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public Builder addKeys(
          int index, boa.types.Output.ResultMap.Builder builderForValue) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          keys_.add(index, builderForValue.build());
          onChanged();
        } else {
          keysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public Builder addAllKeys(
          java.lang.Iterable<? extends boa.types.Output.ResultMap> values) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          super.addAll(values, keys_);
          onChanged();
        } else {
          keysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public Builder clearKeys() {
        if (keysBuilder_ == null) {
          keys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          keysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public Builder removeKeys(int index) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          keys_.remove(index);
          onChanged();
        } else {
          keysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public boa.types.Output.ResultMap.Builder getKeysBuilder(
          int index) {
        return getKeysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public boa.types.Output.ResultMapOrBuilder getKeysOrBuilder(
          int index) {
        if (keysBuilder_ == null) {
          return keys_.get(index);  } else {
          return keysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public java.util.List<? extends boa.types.Output.ResultMapOrBuilder> 
           getKeysOrBuilderList() {
        if (keysBuilder_ != null) {
          return keysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(keys_);
        }
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public boa.types.Output.ResultMap.Builder addKeysBuilder() {
        return getKeysFieldBuilder().addBuilder(
            boa.types.Output.ResultMap.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public boa.types.Output.ResultMap.Builder addKeysBuilder(
          int index) {
        return getKeysFieldBuilder().addBuilder(
            index, boa.types.Output.ResultMap.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.ResultMap keys = 3;</code>
       */
      public java.util.List<boa.types.Output.ResultMap.Builder> 
           getKeysBuilderList() {
        return getKeysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Output.ResultMap, boa.types.Output.ResultMap.Builder, boa.types.Output.ResultMapOrBuilder> 
          getKeysFieldBuilder() {
        if (keysBuilder_ == null) {
          keysBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              boa.types.Output.ResultMap, boa.types.Output.ResultMap.Builder, boa.types.Output.ResultMapOrBuilder>(
                  keys_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          keys_ = null;
        }
        return keysBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:boa.types.ResultMap)
    }

    static {
      defaultInstance = new ResultMap(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:boa.types.ResultMap)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_boa_types_BoaResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_boa_types_BoaResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_boa_types_ResultMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_boa_types_ResultMap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014output.proto\022\tboa.types\"2\n\tBoaResult\022%" +
      "\n\007results\030\001 \003(\0132\024.boa.types.ResultMap\"L\n" +
      "\tResultMap\022\013\n\003key\030\001 \002(\t\022\016\n\006values\030\002 \003(\t\022" +
      "\"\n\004keys\030\003 \003(\0132\024.boa.types.ResultMapB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_boa_types_BoaResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_boa_types_BoaResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_boa_types_BoaResult_descriptor,
              new java.lang.String[] { "Results", });
          internal_static_boa_types_ResultMap_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_boa_types_ResultMap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_boa_types_ResultMap_descriptor,
              new java.lang.String[] { "Key", "Values", "Keys", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
