// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bugs.proto

package sizzle.types;

public final class Bugs {
  private Bugs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BugRepositoryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string url = 1;
    boolean hasUrl();
    String getUrl();
    
    // repeated .sizzle.types.Bug bugs = 2;
    java.util.List<sizzle.types.Bugs.Bug> 
        getBugsList();
    sizzle.types.Bugs.Bug getBugs(int index);
    int getBugsCount();
    java.util.List<? extends sizzle.types.Bugs.BugOrBuilder> 
        getBugsOrBuilderList();
    sizzle.types.Bugs.BugOrBuilder getBugsOrBuilder(
        int index);
  }
  public static final class BugRepository extends
      com.google.protobuf.GeneratedMessage
      implements BugRepositoryOrBuilder {
    // Use BugRepository.newBuilder() to construct.
    private BugRepository(Builder builder) {
      super(builder);
    }
    private BugRepository(boolean noInit) {}
    
    private static final BugRepository defaultInstance;
    public static BugRepository getDefaultInstance() {
      return defaultInstance;
    }
    
    public BugRepository getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sizzle.types.Bugs.internal_static_sizzle_types_BugRepository_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sizzle.types.Bugs.internal_static_sizzle_types_BugRepository_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string url = 1;
    public static final int URL_FIELD_NUMBER = 1;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .sizzle.types.Bug bugs = 2;
    public static final int BUGS_FIELD_NUMBER = 2;
    private java.util.List<sizzle.types.Bugs.Bug> bugs_;
    public java.util.List<sizzle.types.Bugs.Bug> getBugsList() {
      return bugs_;
    }
    public java.util.List<? extends sizzle.types.Bugs.BugOrBuilder> 
        getBugsOrBuilderList() {
      return bugs_;
    }
    public int getBugsCount() {
      return bugs_.size();
    }
    public sizzle.types.Bugs.Bug getBugs(int index) {
      return bugs_.get(index);
    }
    public sizzle.types.Bugs.BugOrBuilder getBugsOrBuilder(
        int index) {
      return bugs_.get(index);
    }
    
    private void initFields() {
      url_ = "";
      bugs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBugsCount(); i++) {
        if (!getBugs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUrlBytes());
      }
      for (int i = 0; i < bugs_.size(); i++) {
        output.writeMessage(2, bugs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUrlBytes());
      }
      for (int i = 0; i < bugs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bugs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sizzle.types.Bugs.BugRepository parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Bugs.BugRepository parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Bugs.BugRepository parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Bugs.BugRepository parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Bugs.BugRepository parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Bugs.BugRepository parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Bugs.BugRepository parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Bugs.BugRepository parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Bugs.BugRepository parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Bugs.BugRepository parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sizzle.types.Bugs.BugRepository prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sizzle.types.Bugs.BugRepositoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sizzle.types.Bugs.internal_static_sizzle_types_BugRepository_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sizzle.types.Bugs.internal_static_sizzle_types_BugRepository_fieldAccessorTable;
      }
      
      // Construct using sizzle.types.Bugs.BugRepository.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBugsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bugsBuilder_ == null) {
          bugs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bugsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sizzle.types.Bugs.BugRepository.getDescriptor();
      }
      
      public sizzle.types.Bugs.BugRepository getDefaultInstanceForType() {
        return sizzle.types.Bugs.BugRepository.getDefaultInstance();
      }
      
      public sizzle.types.Bugs.BugRepository build() {
        sizzle.types.Bugs.BugRepository result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sizzle.types.Bugs.BugRepository buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sizzle.types.Bugs.BugRepository result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sizzle.types.Bugs.BugRepository buildPartial() {
        sizzle.types.Bugs.BugRepository result = new sizzle.types.Bugs.BugRepository(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.url_ = url_;
        if (bugsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            bugs_ = java.util.Collections.unmodifiableList(bugs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.bugs_ = bugs_;
        } else {
          result.bugs_ = bugsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sizzle.types.Bugs.BugRepository) {
          return mergeFrom((sizzle.types.Bugs.BugRepository)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sizzle.types.Bugs.BugRepository other) {
        if (other == sizzle.types.Bugs.BugRepository.getDefaultInstance()) return this;
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (bugsBuilder_ == null) {
          if (!other.bugs_.isEmpty()) {
            if (bugs_.isEmpty()) {
              bugs_ = other.bugs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBugsIsMutable();
              bugs_.addAll(other.bugs_);
            }
            onChanged();
          }
        } else {
          if (!other.bugs_.isEmpty()) {
            if (bugsBuilder_.isEmpty()) {
              bugsBuilder_.dispose();
              bugsBuilder_ = null;
              bugs_ = other.bugs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bugsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBugsFieldBuilder() : null;
            } else {
              bugsBuilder_.addAllMessages(other.bugs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUrl()) {
          
          return false;
        }
        for (int i = 0; i < getBugsCount(); i++) {
          if (!getBugs(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              url_ = input.readBytes();
              break;
            }
            case 18: {
              sizzle.types.Bugs.Bug.Builder subBuilder = sizzle.types.Bugs.Bug.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBugs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string url = 1;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
      }
      
      // repeated .sizzle.types.Bug bugs = 2;
      private java.util.List<sizzle.types.Bugs.Bug> bugs_ =
        java.util.Collections.emptyList();
      private void ensureBugsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          bugs_ = new java.util.ArrayList<sizzle.types.Bugs.Bug>(bugs_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Bugs.Bug, sizzle.types.Bugs.Bug.Builder, sizzle.types.Bugs.BugOrBuilder> bugsBuilder_;
      
      public java.util.List<sizzle.types.Bugs.Bug> getBugsList() {
        if (bugsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bugs_);
        } else {
          return bugsBuilder_.getMessageList();
        }
      }
      public int getBugsCount() {
        if (bugsBuilder_ == null) {
          return bugs_.size();
        } else {
          return bugsBuilder_.getCount();
        }
      }
      public sizzle.types.Bugs.Bug getBugs(int index) {
        if (bugsBuilder_ == null) {
          return bugs_.get(index);
        } else {
          return bugsBuilder_.getMessage(index);
        }
      }
      public Builder setBugs(
          int index, sizzle.types.Bugs.Bug value) {
        if (bugsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBugsIsMutable();
          bugs_.set(index, value);
          onChanged();
        } else {
          bugsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBugs(
          int index, sizzle.types.Bugs.Bug.Builder builderForValue) {
        if (bugsBuilder_ == null) {
          ensureBugsIsMutable();
          bugs_.set(index, builderForValue.build());
          onChanged();
        } else {
          bugsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBugs(sizzle.types.Bugs.Bug value) {
        if (bugsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBugsIsMutable();
          bugs_.add(value);
          onChanged();
        } else {
          bugsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBugs(
          int index, sizzle.types.Bugs.Bug value) {
        if (bugsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBugsIsMutable();
          bugs_.add(index, value);
          onChanged();
        } else {
          bugsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBugs(
          sizzle.types.Bugs.Bug.Builder builderForValue) {
        if (bugsBuilder_ == null) {
          ensureBugsIsMutable();
          bugs_.add(builderForValue.build());
          onChanged();
        } else {
          bugsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBugs(
          int index, sizzle.types.Bugs.Bug.Builder builderForValue) {
        if (bugsBuilder_ == null) {
          ensureBugsIsMutable();
          bugs_.add(index, builderForValue.build());
          onChanged();
        } else {
          bugsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBugs(
          java.lang.Iterable<? extends sizzle.types.Bugs.Bug> values) {
        if (bugsBuilder_ == null) {
          ensureBugsIsMutable();
          super.addAll(values, bugs_);
          onChanged();
        } else {
          bugsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBugs() {
        if (bugsBuilder_ == null) {
          bugs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bugsBuilder_.clear();
        }
        return this;
      }
      public Builder removeBugs(int index) {
        if (bugsBuilder_ == null) {
          ensureBugsIsMutable();
          bugs_.remove(index);
          onChanged();
        } else {
          bugsBuilder_.remove(index);
        }
        return this;
      }
      public sizzle.types.Bugs.Bug.Builder getBugsBuilder(
          int index) {
        return getBugsFieldBuilder().getBuilder(index);
      }
      public sizzle.types.Bugs.BugOrBuilder getBugsOrBuilder(
          int index) {
        if (bugsBuilder_ == null) {
          return bugs_.get(index);  } else {
          return bugsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends sizzle.types.Bugs.BugOrBuilder> 
           getBugsOrBuilderList() {
        if (bugsBuilder_ != null) {
          return bugsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bugs_);
        }
      }
      public sizzle.types.Bugs.Bug.Builder addBugsBuilder() {
        return getBugsFieldBuilder().addBuilder(
            sizzle.types.Bugs.Bug.getDefaultInstance());
      }
      public sizzle.types.Bugs.Bug.Builder addBugsBuilder(
          int index) {
        return getBugsFieldBuilder().addBuilder(
            index, sizzle.types.Bugs.Bug.getDefaultInstance());
      }
      public java.util.List<sizzle.types.Bugs.Bug.Builder> 
           getBugsBuilderList() {
        return getBugsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Bugs.Bug, sizzle.types.Bugs.Bug.Builder, sizzle.types.Bugs.BugOrBuilder> 
          getBugsFieldBuilder() {
        if (bugsBuilder_ == null) {
          bugsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sizzle.types.Bugs.Bug, sizzle.types.Bugs.Bug.Builder, sizzle.types.Bugs.BugOrBuilder>(
                  bugs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          bugs_ = null;
        }
        return bugsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:sizzle.types.BugRepository)
    }
    
    static {
      defaultInstance = new BugRepository(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sizzle.types.BugRepository)
  }
  
  public interface BugOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required .sizzle.types.Person reporter = 2;
    boolean hasReporter();
    sizzle.types.Shared.Person getReporter();
    sizzle.types.Shared.PersonOrBuilder getReporterOrBuilder();
    
    // required uint64 reported_date = 3;
    boolean hasReportedDate();
    long getReportedDate();
    
    // required uint64 closed_date = 4;
    boolean hasClosedDate();
    long getClosedDate();
    
    // required string summary = 5;
    boolean hasSummary();
    String getSummary();
    
    // required string description = 6;
    boolean hasDescription();
    String getDescription();
    
    // required .sizzle.types.Bug.BugStatus status = 7;
    boolean hasStatus();
    sizzle.types.Bugs.Bug.BugStatus getStatus();
    
    // required string severity = 8;
    boolean hasSeverity();
    String getSeverity();
  }
  public static final class Bug extends
      com.google.protobuf.GeneratedMessage
      implements BugOrBuilder {
    // Use Bug.newBuilder() to construct.
    private Bug(Builder builder) {
      super(builder);
    }
    private Bug(boolean noInit) {}
    
    private static final Bug defaultInstance;
    public static Bug getDefaultInstance() {
      return defaultInstance;
    }
    
    public Bug getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sizzle.types.Bugs.internal_static_sizzle_types_Bug_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sizzle.types.Bugs.internal_static_sizzle_types_Bug_fieldAccessorTable;
    }
    
    public enum BugStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      UNKNOWN(0, 1),
      OPEN(1, 2),
      CLOSED(2, 3),
      RESOLVED(3, 4),
      FIXED(4, 5),
      REOPEN(5, 6),
      DUPLICATE(6, 7),
      ;
      
      public static final int UNKNOWN_VALUE = 1;
      public static final int OPEN_VALUE = 2;
      public static final int CLOSED_VALUE = 3;
      public static final int RESOLVED_VALUE = 4;
      public static final int FIXED_VALUE = 5;
      public static final int REOPEN_VALUE = 6;
      public static final int DUPLICATE_VALUE = 7;
      
      
      public final int getNumber() { return value; }
      
      public static BugStatus valueOf(int value) {
        switch (value) {
          case 1: return UNKNOWN;
          case 2: return OPEN;
          case 3: return CLOSED;
          case 4: return RESOLVED;
          case 5: return FIXED;
          case 6: return REOPEN;
          case 7: return DUPLICATE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<BugStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BugStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BugStatus>() {
              public BugStatus findValueByNumber(int number) {
                return BugStatus.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sizzle.types.Bugs.Bug.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final BugStatus[] VALUES = {
        UNKNOWN, OPEN, CLOSED, RESOLVED, FIXED, REOPEN, DUPLICATE, 
      };
      
      public static BugStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private BugStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sizzle.types.Bug.BugStatus)
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .sizzle.types.Person reporter = 2;
    public static final int REPORTER_FIELD_NUMBER = 2;
    private sizzle.types.Shared.Person reporter_;
    public boolean hasReporter() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public sizzle.types.Shared.Person getReporter() {
      return reporter_;
    }
    public sizzle.types.Shared.PersonOrBuilder getReporterOrBuilder() {
      return reporter_;
    }
    
    // required uint64 reported_date = 3;
    public static final int REPORTED_DATE_FIELD_NUMBER = 3;
    private long reportedDate_;
    public boolean hasReportedDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getReportedDate() {
      return reportedDate_;
    }
    
    // required uint64 closed_date = 4;
    public static final int CLOSED_DATE_FIELD_NUMBER = 4;
    private long closedDate_;
    public boolean hasClosedDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getClosedDate() {
      return closedDate_;
    }
    
    // required string summary = 5;
    public static final int SUMMARY_FIELD_NUMBER = 5;
    private java.lang.Object summary_;
    public boolean hasSummary() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSummary() {
      java.lang.Object ref = summary_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          summary_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSummaryBytes() {
      java.lang.Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string description = 6;
    public static final int DESCRIPTION_FIELD_NUMBER = 6;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .sizzle.types.Bug.BugStatus status = 7;
    public static final int STATUS_FIELD_NUMBER = 7;
    private sizzle.types.Bugs.Bug.BugStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public sizzle.types.Bugs.Bug.BugStatus getStatus() {
      return status_;
    }
    
    // required string severity = 8;
    public static final int SEVERITY_FIELD_NUMBER = 8;
    private java.lang.Object severity_;
    public boolean hasSeverity() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getSeverity() {
      java.lang.Object ref = severity_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          severity_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSeverityBytes() {
      java.lang.Object ref = severity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        severity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      reporter_ = sizzle.types.Shared.Person.getDefaultInstance();
      reportedDate_ = 0L;
      closedDate_ = 0L;
      summary_ = "";
      description_ = "";
      status_ = sizzle.types.Bugs.Bug.BugStatus.UNKNOWN;
      severity_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReporter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReportedDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClosedDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSummary()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeverity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getReporter().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, reporter_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, reportedDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, closedDate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSummaryBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, status_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getSeverityBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, reporter_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, reportedDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, closedDate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSummaryBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, status_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getSeverityBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sizzle.types.Bugs.Bug parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Bugs.Bug parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Bugs.Bug parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Bugs.Bug parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Bugs.Bug parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Bugs.Bug parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Bugs.Bug parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Bugs.Bug parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Bugs.Bug parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Bugs.Bug parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sizzle.types.Bugs.Bug prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sizzle.types.Bugs.BugOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sizzle.types.Bugs.internal_static_sizzle_types_Bug_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sizzle.types.Bugs.internal_static_sizzle_types_Bug_fieldAccessorTable;
      }
      
      // Construct using sizzle.types.Bugs.Bug.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReporterFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (reporterBuilder_ == null) {
          reporter_ = sizzle.types.Shared.Person.getDefaultInstance();
        } else {
          reporterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        reportedDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        closedDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        summary_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = sizzle.types.Bugs.Bug.BugStatus.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000040);
        severity_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sizzle.types.Bugs.Bug.getDescriptor();
      }
      
      public sizzle.types.Bugs.Bug getDefaultInstanceForType() {
        return sizzle.types.Bugs.Bug.getDefaultInstance();
      }
      
      public sizzle.types.Bugs.Bug build() {
        sizzle.types.Bugs.Bug result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sizzle.types.Bugs.Bug buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sizzle.types.Bugs.Bug result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sizzle.types.Bugs.Bug buildPartial() {
        sizzle.types.Bugs.Bug result = new sizzle.types.Bugs.Bug(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (reporterBuilder_ == null) {
          result.reporter_ = reporter_;
        } else {
          result.reporter_ = reporterBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reportedDate_ = reportedDate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.closedDate_ = closedDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.summary_ = summary_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.severity_ = severity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sizzle.types.Bugs.Bug) {
          return mergeFrom((sizzle.types.Bugs.Bug)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sizzle.types.Bugs.Bug other) {
        if (other == sizzle.types.Bugs.Bug.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasReporter()) {
          mergeReporter(other.getReporter());
        }
        if (other.hasReportedDate()) {
          setReportedDate(other.getReportedDate());
        }
        if (other.hasClosedDate()) {
          setClosedDate(other.getClosedDate());
        }
        if (other.hasSummary()) {
          setSummary(other.getSummary());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasSeverity()) {
          setSeverity(other.getSeverity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasReporter()) {
          
          return false;
        }
        if (!hasReportedDate()) {
          
          return false;
        }
        if (!hasClosedDate()) {
          
          return false;
        }
        if (!hasSummary()) {
          
          return false;
        }
        if (!hasDescription()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasSeverity()) {
          
          return false;
        }
        if (!getReporter().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              sizzle.types.Shared.Person.Builder subBuilder = sizzle.types.Shared.Person.newBuilder();
              if (hasReporter()) {
                subBuilder.mergeFrom(getReporter());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReporter(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              reportedDate_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              closedDate_ = input.readUInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              summary_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              description_ = input.readBytes();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              sizzle.types.Bugs.Bug.BugStatus value = sizzle.types.Bugs.Bug.BugStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                status_ = value;
              }
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              severity_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required .sizzle.types.Person reporter = 2;
      private sizzle.types.Shared.Person reporter_ = sizzle.types.Shared.Person.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          sizzle.types.Shared.Person, sizzle.types.Shared.Person.Builder, sizzle.types.Shared.PersonOrBuilder> reporterBuilder_;
      public boolean hasReporter() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public sizzle.types.Shared.Person getReporter() {
        if (reporterBuilder_ == null) {
          return reporter_;
        } else {
          return reporterBuilder_.getMessage();
        }
      }
      public Builder setReporter(sizzle.types.Shared.Person value) {
        if (reporterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reporter_ = value;
          onChanged();
        } else {
          reporterBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setReporter(
          sizzle.types.Shared.Person.Builder builderForValue) {
        if (reporterBuilder_ == null) {
          reporter_ = builderForValue.build();
          onChanged();
        } else {
          reporterBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeReporter(sizzle.types.Shared.Person value) {
        if (reporterBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              reporter_ != sizzle.types.Shared.Person.getDefaultInstance()) {
            reporter_ =
              sizzle.types.Shared.Person.newBuilder(reporter_).mergeFrom(value).buildPartial();
          } else {
            reporter_ = value;
          }
          onChanged();
        } else {
          reporterBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearReporter() {
        if (reporterBuilder_ == null) {
          reporter_ = sizzle.types.Shared.Person.getDefaultInstance();
          onChanged();
        } else {
          reporterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public sizzle.types.Shared.Person.Builder getReporterBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getReporterFieldBuilder().getBuilder();
      }
      public sizzle.types.Shared.PersonOrBuilder getReporterOrBuilder() {
        if (reporterBuilder_ != null) {
          return reporterBuilder_.getMessageOrBuilder();
        } else {
          return reporter_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          sizzle.types.Shared.Person, sizzle.types.Shared.Person.Builder, sizzle.types.Shared.PersonOrBuilder> 
          getReporterFieldBuilder() {
        if (reporterBuilder_ == null) {
          reporterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sizzle.types.Shared.Person, sizzle.types.Shared.Person.Builder, sizzle.types.Shared.PersonOrBuilder>(
                  reporter_,
                  getParentForChildren(),
                  isClean());
          reporter_ = null;
        }
        return reporterBuilder_;
      }
      
      // required uint64 reported_date = 3;
      private long reportedDate_ ;
      public boolean hasReportedDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getReportedDate() {
        return reportedDate_;
      }
      public Builder setReportedDate(long value) {
        bitField0_ |= 0x00000004;
        reportedDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearReportedDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reportedDate_ = 0L;
        onChanged();
        return this;
      }
      
      // required uint64 closed_date = 4;
      private long closedDate_ ;
      public boolean hasClosedDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getClosedDate() {
        return closedDate_;
      }
      public Builder setClosedDate(long value) {
        bitField0_ |= 0x00000008;
        closedDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearClosedDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        closedDate_ = 0L;
        onChanged();
        return this;
      }
      
      // required string summary = 5;
      private java.lang.Object summary_ = "";
      public boolean hasSummary() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getSummary() {
        java.lang.Object ref = summary_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          summary_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSummary(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        summary_ = value;
        onChanged();
        return this;
      }
      public Builder clearSummary() {
        bitField0_ = (bitField0_ & ~0x00000010);
        summary_ = getDefaultInstance().getSummary();
        onChanged();
        return this;
      }
      void setSummary(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        summary_ = value;
        onChanged();
      }
      
      // required string description = 6;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000020);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        description_ = value;
        onChanged();
      }
      
      // required .sizzle.types.Bug.BugStatus status = 7;
      private sizzle.types.Bugs.Bug.BugStatus status_ = sizzle.types.Bugs.Bug.BugStatus.UNKNOWN;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public sizzle.types.Bugs.Bug.BugStatus getStatus() {
        return status_;
      }
      public Builder setStatus(sizzle.types.Bugs.Bug.BugStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000040);
        status_ = sizzle.types.Bugs.Bug.BugStatus.UNKNOWN;
        onChanged();
        return this;
      }
      
      // required string severity = 8;
      private java.lang.Object severity_ = "";
      public boolean hasSeverity() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getSeverity() {
        java.lang.Object ref = severity_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          severity_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSeverity(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        severity_ = value;
        onChanged();
        return this;
      }
      public Builder clearSeverity() {
        bitField0_ = (bitField0_ & ~0x00000080);
        severity_ = getDefaultInstance().getSeverity();
        onChanged();
        return this;
      }
      void setSeverity(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        severity_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:sizzle.types.Bug)
    }
    
    static {
      defaultInstance = new Bug(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sizzle.types.Bug)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sizzle_types_BugRepository_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sizzle_types_BugRepository_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sizzle_types_Bug_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sizzle_types_Bug_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbugs.proto\022\014sizzle.types\032\014shared.proto" +
      "\"=\n\rBugRepository\022\013\n\003url\030\001 \002(\t\022\037\n\004bugs\030\002" +
      " \003(\0132\021.sizzle.types.Bug\"\256\002\n\003Bug\022\n\n\002id\030\001 " +
      "\002(\t\022&\n\010reporter\030\002 \002(\0132\024.sizzle.types.Per" +
      "son\022\025\n\rreported_date\030\003 \002(\004\022\023\n\013closed_dat" +
      "e\030\004 \002(\004\022\017\n\007summary\030\005 \002(\t\022\023\n\013description\030" +
      "\006 \002(\t\022+\n\006status\030\007 \002(\0162\033.sizzle.types.Bug" +
      ".BugStatus\022\020\n\010severity\030\010 \002(\t\"b\n\tBugStatu" +
      "s\022\013\n\007UNKNOWN\020\001\022\010\n\004OPEN\020\002\022\n\n\006CLOSED\020\003\022\014\n\010" +
      "RESOLVED\020\004\022\t\n\005FIXED\020\005\022\n\n\006REOPEN\020\006\022\r\n\tDUP",
      "LICATE\020\007B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sizzle_types_BugRepository_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sizzle_types_BugRepository_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sizzle_types_BugRepository_descriptor,
              new java.lang.String[] { "Url", "Bugs", },
              sizzle.types.Bugs.BugRepository.class,
              sizzle.types.Bugs.BugRepository.Builder.class);
          internal_static_sizzle_types_Bug_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sizzle_types_Bug_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sizzle_types_Bug_descriptor,
              new java.lang.String[] { "Id", "Reporter", "ReportedDate", "ClosedDate", "Summary", "Description", "Status", "Severity", },
              sizzle.types.Bugs.Bug.class,
              sizzle.types.Bugs.Bug.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sizzle.types.Shared.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
