// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: code.proto

package sizzle.types;

public final class Code {
  private Code() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CodeRepositoryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string url = 1;
    boolean hasUrl();
    String getUrl();
    
    // required .sizzle.types.CodeRepository.RepositoryKind kind = 2;
    boolean hasKind();
    sizzle.types.Code.CodeRepository.RepositoryKind getKind();
    
    // repeated .sizzle.types.Revision revisions = 3;
    java.util.List<sizzle.types.Code.Revision> 
        getRevisionsList();
    sizzle.types.Code.Revision getRevisions(int index);
    int getRevisionsCount();
    java.util.List<? extends sizzle.types.Code.RevisionOrBuilder> 
        getRevisionsOrBuilderList();
    sizzle.types.Code.RevisionOrBuilder getRevisionsOrBuilder(
        int index);
  }
  public static final class CodeRepository extends
      com.google.protobuf.GeneratedMessage
      implements CodeRepositoryOrBuilder {
    // Use CodeRepository.newBuilder() to construct.
    private CodeRepository(Builder builder) {
      super(builder);
    }
    private CodeRepository(boolean noInit) {}
    
    private static final CodeRepository defaultInstance;
    public static CodeRepository getDefaultInstance() {
      return defaultInstance;
    }
    
    public CodeRepository getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sizzle.types.Code.internal_static_sizzle_types_CodeRepository_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sizzle.types.Code.internal_static_sizzle_types_CodeRepository_fieldAccessorTable;
    }
    
    public enum RepositoryKind
        implements com.google.protobuf.ProtocolMessageEnum {
      UNKNOWN(0, 1),
      SVN(1, 2),
      CVS(2, 3),
      GIT(3, 4),
      HG(4, 5),
      BZR(5, 6),
      ;
      
      public static final int UNKNOWN_VALUE = 1;
      public static final int SVN_VALUE = 2;
      public static final int CVS_VALUE = 3;
      public static final int GIT_VALUE = 4;
      public static final int HG_VALUE = 5;
      public static final int BZR_VALUE = 6;
      
      
      public final int getNumber() { return value; }
      
      public static RepositoryKind valueOf(int value) {
        switch (value) {
          case 1: return UNKNOWN;
          case 2: return SVN;
          case 3: return CVS;
          case 4: return GIT;
          case 5: return HG;
          case 6: return BZR;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<RepositoryKind>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RepositoryKind>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RepositoryKind>() {
              public RepositoryKind findValueByNumber(int number) {
                return RepositoryKind.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sizzle.types.Code.CodeRepository.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final RepositoryKind[] VALUES = {
        UNKNOWN, SVN, CVS, GIT, HG, BZR, 
      };
      
      public static RepositoryKind valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private RepositoryKind(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sizzle.types.CodeRepository.RepositoryKind)
    }
    
    private int bitField0_;
    // required string url = 1;
    public static final int URL_FIELD_NUMBER = 1;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .sizzle.types.CodeRepository.RepositoryKind kind = 2;
    public static final int KIND_FIELD_NUMBER = 2;
    private sizzle.types.Code.CodeRepository.RepositoryKind kind_;
    public boolean hasKind() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public sizzle.types.Code.CodeRepository.RepositoryKind getKind() {
      return kind_;
    }
    
    // repeated .sizzle.types.Revision revisions = 3;
    public static final int REVISIONS_FIELD_NUMBER = 3;
    private java.util.List<sizzle.types.Code.Revision> revisions_;
    public java.util.List<sizzle.types.Code.Revision> getRevisionsList() {
      return revisions_;
    }
    public java.util.List<? extends sizzle.types.Code.RevisionOrBuilder> 
        getRevisionsOrBuilderList() {
      return revisions_;
    }
    public int getRevisionsCount() {
      return revisions_.size();
    }
    public sizzle.types.Code.Revision getRevisions(int index) {
      return revisions_.get(index);
    }
    public sizzle.types.Code.RevisionOrBuilder getRevisionsOrBuilder(
        int index) {
      return revisions_.get(index);
    }
    
    private void initFields() {
      url_ = "";
      kind_ = sizzle.types.Code.CodeRepository.RepositoryKind.UNKNOWN;
      revisions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKind()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRevisionsCount(); i++) {
        if (!getRevisions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, kind_.getNumber());
      }
      for (int i = 0; i < revisions_.size(); i++) {
        output.writeMessage(3, revisions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, kind_.getNumber());
      }
      for (int i = 0; i < revisions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, revisions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sizzle.types.Code.CodeRepository parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Code.CodeRepository parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Code.CodeRepository parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Code.CodeRepository parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Code.CodeRepository parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Code.CodeRepository parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Code.CodeRepository parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Code.CodeRepository parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Code.CodeRepository parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Code.CodeRepository parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sizzle.types.Code.CodeRepository prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sizzle.types.Code.CodeRepositoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sizzle.types.Code.internal_static_sizzle_types_CodeRepository_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sizzle.types.Code.internal_static_sizzle_types_CodeRepository_fieldAccessorTable;
      }
      
      // Construct using sizzle.types.Code.CodeRepository.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRevisionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        kind_ = sizzle.types.Code.CodeRepository.RepositoryKind.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (revisionsBuilder_ == null) {
          revisions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          revisionsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sizzle.types.Code.CodeRepository.getDescriptor();
      }
      
      public sizzle.types.Code.CodeRepository getDefaultInstanceForType() {
        return sizzle.types.Code.CodeRepository.getDefaultInstance();
      }
      
      public sizzle.types.Code.CodeRepository build() {
        sizzle.types.Code.CodeRepository result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sizzle.types.Code.CodeRepository buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sizzle.types.Code.CodeRepository result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sizzle.types.Code.CodeRepository buildPartial() {
        sizzle.types.Code.CodeRepository result = new sizzle.types.Code.CodeRepository(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.kind_ = kind_;
        if (revisionsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            revisions_ = java.util.Collections.unmodifiableList(revisions_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.revisions_ = revisions_;
        } else {
          result.revisions_ = revisionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sizzle.types.Code.CodeRepository) {
          return mergeFrom((sizzle.types.Code.CodeRepository)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sizzle.types.Code.CodeRepository other) {
        if (other == sizzle.types.Code.CodeRepository.getDefaultInstance()) return this;
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasKind()) {
          setKind(other.getKind());
        }
        if (revisionsBuilder_ == null) {
          if (!other.revisions_.isEmpty()) {
            if (revisions_.isEmpty()) {
              revisions_ = other.revisions_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRevisionsIsMutable();
              revisions_.addAll(other.revisions_);
            }
            onChanged();
          }
        } else {
          if (!other.revisions_.isEmpty()) {
            if (revisionsBuilder_.isEmpty()) {
              revisionsBuilder_.dispose();
              revisionsBuilder_ = null;
              revisions_ = other.revisions_;
              bitField0_ = (bitField0_ & ~0x00000004);
              revisionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRevisionsFieldBuilder() : null;
            } else {
              revisionsBuilder_.addAllMessages(other.revisions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasKind()) {
          
          return false;
        }
        for (int i = 0; i < getRevisionsCount(); i++) {
          if (!getRevisions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              url_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              sizzle.types.Code.CodeRepository.RepositoryKind value = sizzle.types.Code.CodeRepository.RepositoryKind.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                kind_ = value;
              }
              break;
            }
            case 26: {
              sizzle.types.Code.Revision.Builder subBuilder = sizzle.types.Code.Revision.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRevisions(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string url = 1;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
      }
      
      // required .sizzle.types.CodeRepository.RepositoryKind kind = 2;
      private sizzle.types.Code.CodeRepository.RepositoryKind kind_ = sizzle.types.Code.CodeRepository.RepositoryKind.UNKNOWN;
      public boolean hasKind() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public sizzle.types.Code.CodeRepository.RepositoryKind getKind() {
        return kind_;
      }
      public Builder setKind(sizzle.types.Code.CodeRepository.RepositoryKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        kind_ = value;
        onChanged();
        return this;
      }
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000002);
        kind_ = sizzle.types.Code.CodeRepository.RepositoryKind.UNKNOWN;
        onChanged();
        return this;
      }
      
      // repeated .sizzle.types.Revision revisions = 3;
      private java.util.List<sizzle.types.Code.Revision> revisions_ =
        java.util.Collections.emptyList();
      private void ensureRevisionsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          revisions_ = new java.util.ArrayList<sizzle.types.Code.Revision>(revisions_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Code.Revision, sizzle.types.Code.Revision.Builder, sizzle.types.Code.RevisionOrBuilder> revisionsBuilder_;
      
      public java.util.List<sizzle.types.Code.Revision> getRevisionsList() {
        if (revisionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(revisions_);
        } else {
          return revisionsBuilder_.getMessageList();
        }
      }
      public int getRevisionsCount() {
        if (revisionsBuilder_ == null) {
          return revisions_.size();
        } else {
          return revisionsBuilder_.getCount();
        }
      }
      public sizzle.types.Code.Revision getRevisions(int index) {
        if (revisionsBuilder_ == null) {
          return revisions_.get(index);
        } else {
          return revisionsBuilder_.getMessage(index);
        }
      }
      public Builder setRevisions(
          int index, sizzle.types.Code.Revision value) {
        if (revisionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRevisionsIsMutable();
          revisions_.set(index, value);
          onChanged();
        } else {
          revisionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRevisions(
          int index, sizzle.types.Code.Revision.Builder builderForValue) {
        if (revisionsBuilder_ == null) {
          ensureRevisionsIsMutable();
          revisions_.set(index, builderForValue.build());
          onChanged();
        } else {
          revisionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRevisions(sizzle.types.Code.Revision value) {
        if (revisionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRevisionsIsMutable();
          revisions_.add(value);
          onChanged();
        } else {
          revisionsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRevisions(
          int index, sizzle.types.Code.Revision value) {
        if (revisionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRevisionsIsMutable();
          revisions_.add(index, value);
          onChanged();
        } else {
          revisionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRevisions(
          sizzle.types.Code.Revision.Builder builderForValue) {
        if (revisionsBuilder_ == null) {
          ensureRevisionsIsMutable();
          revisions_.add(builderForValue.build());
          onChanged();
        } else {
          revisionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRevisions(
          int index, sizzle.types.Code.Revision.Builder builderForValue) {
        if (revisionsBuilder_ == null) {
          ensureRevisionsIsMutable();
          revisions_.add(index, builderForValue.build());
          onChanged();
        } else {
          revisionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRevisions(
          java.lang.Iterable<? extends sizzle.types.Code.Revision> values) {
        if (revisionsBuilder_ == null) {
          ensureRevisionsIsMutable();
          super.addAll(values, revisions_);
          onChanged();
        } else {
          revisionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRevisions() {
        if (revisionsBuilder_ == null) {
          revisions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          revisionsBuilder_.clear();
        }
        return this;
      }
      public Builder removeRevisions(int index) {
        if (revisionsBuilder_ == null) {
          ensureRevisionsIsMutable();
          revisions_.remove(index);
          onChanged();
        } else {
          revisionsBuilder_.remove(index);
        }
        return this;
      }
      public sizzle.types.Code.Revision.Builder getRevisionsBuilder(
          int index) {
        return getRevisionsFieldBuilder().getBuilder(index);
      }
      public sizzle.types.Code.RevisionOrBuilder getRevisionsOrBuilder(
          int index) {
        if (revisionsBuilder_ == null) {
          return revisions_.get(index);  } else {
          return revisionsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends sizzle.types.Code.RevisionOrBuilder> 
           getRevisionsOrBuilderList() {
        if (revisionsBuilder_ != null) {
          return revisionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(revisions_);
        }
      }
      public sizzle.types.Code.Revision.Builder addRevisionsBuilder() {
        return getRevisionsFieldBuilder().addBuilder(
            sizzle.types.Code.Revision.getDefaultInstance());
      }
      public sizzle.types.Code.Revision.Builder addRevisionsBuilder(
          int index) {
        return getRevisionsFieldBuilder().addBuilder(
            index, sizzle.types.Code.Revision.getDefaultInstance());
      }
      public java.util.List<sizzle.types.Code.Revision.Builder> 
           getRevisionsBuilderList() {
        return getRevisionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Code.Revision, sizzle.types.Code.Revision.Builder, sizzle.types.Code.RevisionOrBuilder> 
          getRevisionsFieldBuilder() {
        if (revisionsBuilder_ == null) {
          revisionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sizzle.types.Code.Revision, sizzle.types.Code.Revision.Builder, sizzle.types.Code.RevisionOrBuilder>(
                  revisions_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          revisions_ = null;
        }
        return revisionsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:sizzle.types.CodeRepository)
    }
    
    static {
      defaultInstance = new CodeRepository(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sizzle.types.CodeRepository)
  }
  
  public interface RevisionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required .sizzle.types.Person author = 2;
    boolean hasAuthor();
    sizzle.types.Shared.Person getAuthor();
    sizzle.types.Shared.PersonOrBuilder getAuthorOrBuilder();
    
    // required .sizzle.types.Person committer = 3;
    boolean hasCommitter();
    sizzle.types.Shared.Person getCommitter();
    sizzle.types.Shared.PersonOrBuilder getCommitterOrBuilder();
    
    // required uint64 commit_date = 4;
    boolean hasCommitDate();
    long getCommitDate();
    
    // required string log = 5;
    boolean hasLog();
    String getLog();
    
    // repeated .sizzle.types.File files = 6;
    java.util.List<sizzle.types.Ast.File> 
        getFilesList();
    sizzle.types.Ast.File getFiles(int index);
    int getFilesCount();
    java.util.List<? extends sizzle.types.Ast.FileOrBuilder> 
        getFilesOrBuilderList();
    sizzle.types.Ast.FileOrBuilder getFilesOrBuilder(
        int index);
  }
  public static final class Revision extends
      com.google.protobuf.GeneratedMessage
      implements RevisionOrBuilder {
    // Use Revision.newBuilder() to construct.
    private Revision(Builder builder) {
      super(builder);
    }
    private Revision(boolean noInit) {}
    
    private static final Revision defaultInstance;
    public static Revision getDefaultInstance() {
      return defaultInstance;
    }
    
    public Revision getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sizzle.types.Code.internal_static_sizzle_types_Revision_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sizzle.types.Code.internal_static_sizzle_types_Revision_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required .sizzle.types.Person author = 2;
    public static final int AUTHOR_FIELD_NUMBER = 2;
    private sizzle.types.Shared.Person author_;
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public sizzle.types.Shared.Person getAuthor() {
      return author_;
    }
    public sizzle.types.Shared.PersonOrBuilder getAuthorOrBuilder() {
      return author_;
    }
    
    // required .sizzle.types.Person committer = 3;
    public static final int COMMITTER_FIELD_NUMBER = 3;
    private sizzle.types.Shared.Person committer_;
    public boolean hasCommitter() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public sizzle.types.Shared.Person getCommitter() {
      return committer_;
    }
    public sizzle.types.Shared.PersonOrBuilder getCommitterOrBuilder() {
      return committer_;
    }
    
    // required uint64 commit_date = 4;
    public static final int COMMIT_DATE_FIELD_NUMBER = 4;
    private long commitDate_;
    public boolean hasCommitDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getCommitDate() {
      return commitDate_;
    }
    
    // required string log = 5;
    public static final int LOG_FIELD_NUMBER = 5;
    private java.lang.Object log_;
    public boolean hasLog() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getLog() {
      java.lang.Object ref = log_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          log_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLogBytes() {
      java.lang.Object ref = log_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        log_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .sizzle.types.File files = 6;
    public static final int FILES_FIELD_NUMBER = 6;
    private java.util.List<sizzle.types.Ast.File> files_;
    public java.util.List<sizzle.types.Ast.File> getFilesList() {
      return files_;
    }
    public java.util.List<? extends sizzle.types.Ast.FileOrBuilder> 
        getFilesOrBuilderList() {
      return files_;
    }
    public int getFilesCount() {
      return files_.size();
    }
    public sizzle.types.Ast.File getFiles(int index) {
      return files_.get(index);
    }
    public sizzle.types.Ast.FileOrBuilder getFilesOrBuilder(
        int index) {
      return files_.get(index);
    }
    
    private void initFields() {
      id_ = 0;
      author_ = sizzle.types.Shared.Person.getDefaultInstance();
      committer_ = sizzle.types.Shared.Person.getDefaultInstance();
      commitDate_ = 0L;
      log_ = "";
      files_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAuthor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommitter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommitDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLog()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getAuthor().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCommitter().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFilesCount(); i++) {
        if (!getFiles(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, author_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, committer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, commitDate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getLogBytes());
      }
      for (int i = 0; i < files_.size(); i++) {
        output.writeMessage(6, files_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, author_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, committer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, commitDate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLogBytes());
      }
      for (int i = 0; i < files_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, files_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sizzle.types.Code.Revision parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Code.Revision parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Code.Revision parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Code.Revision parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Code.Revision parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Code.Revision parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Code.Revision parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Code.Revision parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Code.Revision parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Code.Revision parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sizzle.types.Code.Revision prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sizzle.types.Code.RevisionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sizzle.types.Code.internal_static_sizzle_types_Revision_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sizzle.types.Code.internal_static_sizzle_types_Revision_fieldAccessorTable;
      }
      
      // Construct using sizzle.types.Code.Revision.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAuthorFieldBuilder();
          getCommitterFieldBuilder();
          getFilesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (authorBuilder_ == null) {
          author_ = sizzle.types.Shared.Person.getDefaultInstance();
        } else {
          authorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (committerBuilder_ == null) {
          committer_ = sizzle.types.Shared.Person.getDefaultInstance();
        } else {
          committerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        commitDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        log_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          filesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sizzle.types.Code.Revision.getDescriptor();
      }
      
      public sizzle.types.Code.Revision getDefaultInstanceForType() {
        return sizzle.types.Code.Revision.getDefaultInstance();
      }
      
      public sizzle.types.Code.Revision build() {
        sizzle.types.Code.Revision result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sizzle.types.Code.Revision buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sizzle.types.Code.Revision result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sizzle.types.Code.Revision buildPartial() {
        sizzle.types.Code.Revision result = new sizzle.types.Code.Revision(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (authorBuilder_ == null) {
          result.author_ = author_;
        } else {
          result.author_ = authorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (committerBuilder_ == null) {
          result.committer_ = committer_;
        } else {
          result.committer_ = committerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.commitDate_ = commitDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.log_ = log_;
        if (filesBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            files_ = java.util.Collections.unmodifiableList(files_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.files_ = files_;
        } else {
          result.files_ = filesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sizzle.types.Code.Revision) {
          return mergeFrom((sizzle.types.Code.Revision)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sizzle.types.Code.Revision other) {
        if (other == sizzle.types.Code.Revision.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAuthor()) {
          mergeAuthor(other.getAuthor());
        }
        if (other.hasCommitter()) {
          mergeCommitter(other.getCommitter());
        }
        if (other.hasCommitDate()) {
          setCommitDate(other.getCommitDate());
        }
        if (other.hasLog()) {
          setLog(other.getLog());
        }
        if (filesBuilder_ == null) {
          if (!other.files_.isEmpty()) {
            if (files_.isEmpty()) {
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureFilesIsMutable();
              files_.addAll(other.files_);
            }
            onChanged();
          }
        } else {
          if (!other.files_.isEmpty()) {
            if (filesBuilder_.isEmpty()) {
              filesBuilder_.dispose();
              filesBuilder_ = null;
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000020);
              filesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFilesFieldBuilder() : null;
            } else {
              filesBuilder_.addAllMessages(other.files_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAuthor()) {
          
          return false;
        }
        if (!hasCommitter()) {
          
          return false;
        }
        if (!hasCommitDate()) {
          
          return false;
        }
        if (!hasLog()) {
          
          return false;
        }
        if (!getAuthor().isInitialized()) {
          
          return false;
        }
        if (!getCommitter().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getFilesCount(); i++) {
          if (!getFiles(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              sizzle.types.Shared.Person.Builder subBuilder = sizzle.types.Shared.Person.newBuilder();
              if (hasAuthor()) {
                subBuilder.mergeFrom(getAuthor());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAuthor(subBuilder.buildPartial());
              break;
            }
            case 26: {
              sizzle.types.Shared.Person.Builder subBuilder = sizzle.types.Shared.Person.newBuilder();
              if (hasCommitter()) {
                subBuilder.mergeFrom(getCommitter());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommitter(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              commitDate_ = input.readUInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              log_ = input.readBytes();
              break;
            }
            case 50: {
              sizzle.types.Ast.File.Builder subBuilder = sizzle.types.Ast.File.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFiles(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required .sizzle.types.Person author = 2;
      private sizzle.types.Shared.Person author_ = sizzle.types.Shared.Person.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          sizzle.types.Shared.Person, sizzle.types.Shared.Person.Builder, sizzle.types.Shared.PersonOrBuilder> authorBuilder_;
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public sizzle.types.Shared.Person getAuthor() {
        if (authorBuilder_ == null) {
          return author_;
        } else {
          return authorBuilder_.getMessage();
        }
      }
      public Builder setAuthor(sizzle.types.Shared.Person value) {
        if (authorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          author_ = value;
          onChanged();
        } else {
          authorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setAuthor(
          sizzle.types.Shared.Person.Builder builderForValue) {
        if (authorBuilder_ == null) {
          author_ = builderForValue.build();
          onChanged();
        } else {
          authorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeAuthor(sizzle.types.Shared.Person value) {
        if (authorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              author_ != sizzle.types.Shared.Person.getDefaultInstance()) {
            author_ =
              sizzle.types.Shared.Person.newBuilder(author_).mergeFrom(value).buildPartial();
          } else {
            author_ = value;
          }
          onChanged();
        } else {
          authorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearAuthor() {
        if (authorBuilder_ == null) {
          author_ = sizzle.types.Shared.Person.getDefaultInstance();
          onChanged();
        } else {
          authorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public sizzle.types.Shared.Person.Builder getAuthorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getAuthorFieldBuilder().getBuilder();
      }
      public sizzle.types.Shared.PersonOrBuilder getAuthorOrBuilder() {
        if (authorBuilder_ != null) {
          return authorBuilder_.getMessageOrBuilder();
        } else {
          return author_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          sizzle.types.Shared.Person, sizzle.types.Shared.Person.Builder, sizzle.types.Shared.PersonOrBuilder> 
          getAuthorFieldBuilder() {
        if (authorBuilder_ == null) {
          authorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sizzle.types.Shared.Person, sizzle.types.Shared.Person.Builder, sizzle.types.Shared.PersonOrBuilder>(
                  author_,
                  getParentForChildren(),
                  isClean());
          author_ = null;
        }
        return authorBuilder_;
      }
      
      // required .sizzle.types.Person committer = 3;
      private sizzle.types.Shared.Person committer_ = sizzle.types.Shared.Person.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          sizzle.types.Shared.Person, sizzle.types.Shared.Person.Builder, sizzle.types.Shared.PersonOrBuilder> committerBuilder_;
      public boolean hasCommitter() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public sizzle.types.Shared.Person getCommitter() {
        if (committerBuilder_ == null) {
          return committer_;
        } else {
          return committerBuilder_.getMessage();
        }
      }
      public Builder setCommitter(sizzle.types.Shared.Person value) {
        if (committerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          committer_ = value;
          onChanged();
        } else {
          committerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setCommitter(
          sizzle.types.Shared.Person.Builder builderForValue) {
        if (committerBuilder_ == null) {
          committer_ = builderForValue.build();
          onChanged();
        } else {
          committerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeCommitter(sizzle.types.Shared.Person value) {
        if (committerBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              committer_ != sizzle.types.Shared.Person.getDefaultInstance()) {
            committer_ =
              sizzle.types.Shared.Person.newBuilder(committer_).mergeFrom(value).buildPartial();
          } else {
            committer_ = value;
          }
          onChanged();
        } else {
          committerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearCommitter() {
        if (committerBuilder_ == null) {
          committer_ = sizzle.types.Shared.Person.getDefaultInstance();
          onChanged();
        } else {
          committerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public sizzle.types.Shared.Person.Builder getCommitterBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCommitterFieldBuilder().getBuilder();
      }
      public sizzle.types.Shared.PersonOrBuilder getCommitterOrBuilder() {
        if (committerBuilder_ != null) {
          return committerBuilder_.getMessageOrBuilder();
        } else {
          return committer_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          sizzle.types.Shared.Person, sizzle.types.Shared.Person.Builder, sizzle.types.Shared.PersonOrBuilder> 
          getCommitterFieldBuilder() {
        if (committerBuilder_ == null) {
          committerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sizzle.types.Shared.Person, sizzle.types.Shared.Person.Builder, sizzle.types.Shared.PersonOrBuilder>(
                  committer_,
                  getParentForChildren(),
                  isClean());
          committer_ = null;
        }
        return committerBuilder_;
      }
      
      // required uint64 commit_date = 4;
      private long commitDate_ ;
      public boolean hasCommitDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getCommitDate() {
        return commitDate_;
      }
      public Builder setCommitDate(long value) {
        bitField0_ |= 0x00000008;
        commitDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommitDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        commitDate_ = 0L;
        onChanged();
        return this;
      }
      
      // required string log = 5;
      private java.lang.Object log_ = "";
      public boolean hasLog() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getLog() {
        java.lang.Object ref = log_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          log_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLog(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        log_ = value;
        onChanged();
        return this;
      }
      public Builder clearLog() {
        bitField0_ = (bitField0_ & ~0x00000010);
        log_ = getDefaultInstance().getLog();
        onChanged();
        return this;
      }
      void setLog(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        log_ = value;
        onChanged();
      }
      
      // repeated .sizzle.types.File files = 6;
      private java.util.List<sizzle.types.Ast.File> files_ =
        java.util.Collections.emptyList();
      private void ensureFilesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          files_ = new java.util.ArrayList<sizzle.types.Ast.File>(files_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Ast.File, sizzle.types.Ast.File.Builder, sizzle.types.Ast.FileOrBuilder> filesBuilder_;
      
      public java.util.List<sizzle.types.Ast.File> getFilesList() {
        if (filesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(files_);
        } else {
          return filesBuilder_.getMessageList();
        }
      }
      public int getFilesCount() {
        if (filesBuilder_ == null) {
          return files_.size();
        } else {
          return filesBuilder_.getCount();
        }
      }
      public sizzle.types.Ast.File getFiles(int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);
        } else {
          return filesBuilder_.getMessage(index);
        }
      }
      public Builder setFiles(
          int index, sizzle.types.Ast.File value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.set(index, value);
          onChanged();
        } else {
          filesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFiles(
          int index, sizzle.types.Ast.File.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.set(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFiles(sizzle.types.Ast.File value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(value);
          onChanged();
        } else {
          filesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFiles(
          int index, sizzle.types.Ast.File value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(index, value);
          onChanged();
        } else {
          filesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFiles(
          sizzle.types.Ast.File.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFiles(
          int index, sizzle.types.Ast.File.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFiles(
          java.lang.Iterable<? extends sizzle.types.Ast.File> values) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          super.addAll(values, files_);
          onChanged();
        } else {
          filesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFiles() {
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          filesBuilder_.clear();
        }
        return this;
      }
      public Builder removeFiles(int index) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.remove(index);
          onChanged();
        } else {
          filesBuilder_.remove(index);
        }
        return this;
      }
      public sizzle.types.Ast.File.Builder getFilesBuilder(
          int index) {
        return getFilesFieldBuilder().getBuilder(index);
      }
      public sizzle.types.Ast.FileOrBuilder getFilesOrBuilder(
          int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);  } else {
          return filesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends sizzle.types.Ast.FileOrBuilder> 
           getFilesOrBuilderList() {
        if (filesBuilder_ != null) {
          return filesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(files_);
        }
      }
      public sizzle.types.Ast.File.Builder addFilesBuilder() {
        return getFilesFieldBuilder().addBuilder(
            sizzle.types.Ast.File.getDefaultInstance());
      }
      public sizzle.types.Ast.File.Builder addFilesBuilder(
          int index) {
        return getFilesFieldBuilder().addBuilder(
            index, sizzle.types.Ast.File.getDefaultInstance());
      }
      public java.util.List<sizzle.types.Ast.File.Builder> 
           getFilesBuilderList() {
        return getFilesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Ast.File, sizzle.types.Ast.File.Builder, sizzle.types.Ast.FileOrBuilder> 
          getFilesFieldBuilder() {
        if (filesBuilder_ == null) {
          filesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sizzle.types.Ast.File, sizzle.types.Ast.File.Builder, sizzle.types.Ast.FileOrBuilder>(
                  files_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          files_ = null;
        }
        return filesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:sizzle.types.Revision)
    }
    
    static {
      defaultInstance = new Revision(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sizzle.types.Revision)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sizzle_types_CodeRepository_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sizzle_types_CodeRepository_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sizzle_types_Revision_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sizzle_types_Revision_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncode.proto\022\014sizzle.types\032\tast.proto\032\014s" +
      "hared.proto\"\316\001\n\016CodeRepository\022\013\n\003url\030\001 " +
      "\002(\t\0229\n\004kind\030\002 \002(\0162+.sizzle.types.CodeRep" +
      "ository.RepositoryKind\022)\n\trevisions\030\003 \003(" +
      "\0132\026.sizzle.types.Revision\"I\n\016RepositoryK" +
      "ind\022\013\n\007UNKNOWN\020\001\022\007\n\003SVN\020\002\022\007\n\003CVS\020\003\022\007\n\003GI" +
      "T\020\004\022\006\n\002HG\020\005\022\007\n\003BZR\020\006\"\252\001\n\010Revision\022\n\n\002id\030" +
      "\001 \002(\005\022$\n\006author\030\002 \002(\0132\024.sizzle.types.Per" +
      "son\022\'\n\tcommitter\030\003 \002(\0132\024.sizzle.types.Pe" +
      "rson\022\023\n\013commit_date\030\004 \002(\004\022\013\n\003log\030\005 \002(\t\022!",
      "\n\005files\030\006 \003(\0132\022.sizzle.types.FileB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sizzle_types_CodeRepository_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sizzle_types_CodeRepository_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sizzle_types_CodeRepository_descriptor,
              new java.lang.String[] { "Url", "Kind", "Revisions", },
              sizzle.types.Code.CodeRepository.class,
              sizzle.types.Code.CodeRepository.Builder.class);
          internal_static_sizzle_types_Revision_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sizzle_types_Revision_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sizzle_types_Revision_descriptor,
              new java.lang.String[] { "Id", "Author", "Committer", "CommitDate", "Log", "Files", },
              sizzle.types.Code.Revision.class,
              sizzle.types.Code.Revision.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sizzle.types.Ast.getDescriptor(),
          sizzle.types.Shared.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
