// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package boa.types.transportation;

public final class State {
  private State() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code boa.types.transportation.STATE}
   */
  public enum STATE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Alabama = 1;</code>
     */
    Alabama(0, 1),
    /**
     * <code>Montana = 30;</code>
     */
    Montana(1, 30),
    /**
     * <code>Nebraska = 31;</code>
     */
    Nebraska(2, 31),
    /**
     * <code>Alaska = 2;</code>
     */
    Alaska(3, 2),
    /**
     * <code>Nevada = 32;</code>
     */
    Nevada(4, 32),
    /**
     * <code>Arizona = 4;</code>
     */
    Arizona(5, 4),
    /**
     * <code>New_Hampshire = 33;</code>
     */
    New_Hampshire(6, 33),
    /**
     * <code>Arkansas = 5;</code>
     */
    Arkansas(7, 5),
    /**
     * <code>New_Jersey = 34;</code>
     */
    New_Jersey(8, 34),
    /**
     * <code>California = 6;</code>
     */
    California(9, 6),
    /**
     * <code>New_Mexico = 35;</code>
     */
    New_Mexico(10, 35),
    /**
     * <code>Colorado = 8;</code>
     */
    Colorado(11, 8),
    /**
     * <code>New_York = 36;</code>
     */
    New_York(12, 36),
    /**
     * <code>Connecticut = 9;</code>
     */
    Connecticut(13, 9),
    /**
     * <code>North_Carolina = 37;</code>
     */
    North_Carolina(14, 37),
    /**
     * <code>Delaware = 10;</code>
     */
    Delaware(15, 10),
    /**
     * <code>North_Dakota = 38;</code>
     */
    North_Dakota(16, 38),
    /**
     * <code>District_of_Columbia = 11;</code>
     */
    District_of_Columbia(17, 11),
    /**
     * <code>Ohio = 39;</code>
     */
    Ohio(18, 39),
    /**
     * <code>Florida = 12;</code>
     */
    Florida(19, 12),
    /**
     * <code>Oklahoma = 40;</code>
     */
    Oklahoma(20, 40),
    /**
     * <code>Georgia = 13;</code>
     */
    Georgia(21, 13),
    /**
     * <code>Oregon = 41;</code>
     */
    Oregon(22, 41),
    /**
     * <code>Hawaii = 15;</code>
     */
    Hawaii(23, 15),
    /**
     * <code>Pennsylvania = 42;</code>
     */
    Pennsylvania(24, 42),
    /**
     * <code>Idaho = 16;</code>
     */
    Idaho(25, 16),
    /**
     * <code>Puerto_Rico = 43;</code>
     */
    Puerto_Rico(26, 43),
    /**
     * <code>Illinois = 17;</code>
     */
    Illinois(27, 17),
    /**
     * <code>Rhode_Island = 44;</code>
     */
    Rhode_Island(28, 44),
    /**
     * <code>Indiana = 18;</code>
     */
    Indiana(29, 18),
    /**
     * <code>South_Carolina = 45;</code>
     */
    South_Carolina(30, 45),
    /**
     * <code>Iowa = 19;</code>
     */
    Iowa(31, 19),
    /**
     * <code>South_Dakota = 46;</code>
     */
    South_Dakota(32, 46),
    /**
     * <code>Kansas = 20;</code>
     */
    Kansas(33, 20),
    /**
     * <code>Tennessee = 47;</code>
     */
    Tennessee(34, 47),
    /**
     * <code>Kentucky = 21;</code>
     */
    Kentucky(35, 21),
    /**
     * <code>Texas = 48;</code>
     */
    Texas(36, 48),
    /**
     * <code>Louisiana = 22;</code>
     */
    Louisiana(37, 22),
    /**
     * <code>Utah = 49;</code>
     */
    Utah(38, 49),
    /**
     * <code>Maine = 23;</code>
     */
    Maine(39, 23),
    /**
     * <code>Vermont = 50;</code>
     */
    Vermont(40, 50),
    /**
     * <code>Maryland = 24;</code>
     */
    Maryland(41, 24),
    /**
     * <code>Virgin_Islands = 52;</code>
     */
    Virgin_Islands(42, 52),
    /**
     * <code>Massachusetts = 25;</code>
     */
    Massachusetts(43, 25),
    /**
     * <code>Virginia = 51;</code>
     */
    Virginia(44, 51),
    /**
     * <code>Michigan = 26;</code>
     */
    Michigan(45, 26),
    /**
     * <code>Washington = 53;</code>
     */
    Washington(46, 53),
    /**
     * <code>Minnesota = 27;</code>
     */
    Minnesota(47, 27),
    /**
     * <code>West_Virginia = 54;</code>
     */
    West_Virginia(48, 54),
    /**
     * <code>Mississippi = 28;</code>
     */
    Mississippi(49, 28),
    /**
     * <code>Wisconsin = 55;</code>
     */
    Wisconsin(50, 55),
    /**
     * <code>Missouri = 29;</code>
     */
    Missouri(51, 29),
    /**
     * <code>Wyoming = 56;</code>
     */
    Wyoming(52, 56),
    ;

    /**
     * <code>Alabama = 1;</code>
     */
    public static final int Alabama_VALUE = 1;
    /**
     * <code>Montana = 30;</code>
     */
    public static final int Montana_VALUE = 30;
    /**
     * <code>Nebraska = 31;</code>
     */
    public static final int Nebraska_VALUE = 31;
    /**
     * <code>Alaska = 2;</code>
     */
    public static final int Alaska_VALUE = 2;
    /**
     * <code>Nevada = 32;</code>
     */
    public static final int Nevada_VALUE = 32;
    /**
     * <code>Arizona = 4;</code>
     */
    public static final int Arizona_VALUE = 4;
    /**
     * <code>New_Hampshire = 33;</code>
     */
    public static final int New_Hampshire_VALUE = 33;
    /**
     * <code>Arkansas = 5;</code>
     */
    public static final int Arkansas_VALUE = 5;
    /**
     * <code>New_Jersey = 34;</code>
     */
    public static final int New_Jersey_VALUE = 34;
    /**
     * <code>California = 6;</code>
     */
    public static final int California_VALUE = 6;
    /**
     * <code>New_Mexico = 35;</code>
     */
    public static final int New_Mexico_VALUE = 35;
    /**
     * <code>Colorado = 8;</code>
     */
    public static final int Colorado_VALUE = 8;
    /**
     * <code>New_York = 36;</code>
     */
    public static final int New_York_VALUE = 36;
    /**
     * <code>Connecticut = 9;</code>
     */
    public static final int Connecticut_VALUE = 9;
    /**
     * <code>North_Carolina = 37;</code>
     */
    public static final int North_Carolina_VALUE = 37;
    /**
     * <code>Delaware = 10;</code>
     */
    public static final int Delaware_VALUE = 10;
    /**
     * <code>North_Dakota = 38;</code>
     */
    public static final int North_Dakota_VALUE = 38;
    /**
     * <code>District_of_Columbia = 11;</code>
     */
    public static final int District_of_Columbia_VALUE = 11;
    /**
     * <code>Ohio = 39;</code>
     */
    public static final int Ohio_VALUE = 39;
    /**
     * <code>Florida = 12;</code>
     */
    public static final int Florida_VALUE = 12;
    /**
     * <code>Oklahoma = 40;</code>
     */
    public static final int Oklahoma_VALUE = 40;
    /**
     * <code>Georgia = 13;</code>
     */
    public static final int Georgia_VALUE = 13;
    /**
     * <code>Oregon = 41;</code>
     */
    public static final int Oregon_VALUE = 41;
    /**
     * <code>Hawaii = 15;</code>
     */
    public static final int Hawaii_VALUE = 15;
    /**
     * <code>Pennsylvania = 42;</code>
     */
    public static final int Pennsylvania_VALUE = 42;
    /**
     * <code>Idaho = 16;</code>
     */
    public static final int Idaho_VALUE = 16;
    /**
     * <code>Puerto_Rico = 43;</code>
     */
    public static final int Puerto_Rico_VALUE = 43;
    /**
     * <code>Illinois = 17;</code>
     */
    public static final int Illinois_VALUE = 17;
    /**
     * <code>Rhode_Island = 44;</code>
     */
    public static final int Rhode_Island_VALUE = 44;
    /**
     * <code>Indiana = 18;</code>
     */
    public static final int Indiana_VALUE = 18;
    /**
     * <code>South_Carolina = 45;</code>
     */
    public static final int South_Carolina_VALUE = 45;
    /**
     * <code>Iowa = 19;</code>
     */
    public static final int Iowa_VALUE = 19;
    /**
     * <code>South_Dakota = 46;</code>
     */
    public static final int South_Dakota_VALUE = 46;
    /**
     * <code>Kansas = 20;</code>
     */
    public static final int Kansas_VALUE = 20;
    /**
     * <code>Tennessee = 47;</code>
     */
    public static final int Tennessee_VALUE = 47;
    /**
     * <code>Kentucky = 21;</code>
     */
    public static final int Kentucky_VALUE = 21;
    /**
     * <code>Texas = 48;</code>
     */
    public static final int Texas_VALUE = 48;
    /**
     * <code>Louisiana = 22;</code>
     */
    public static final int Louisiana_VALUE = 22;
    /**
     * <code>Utah = 49;</code>
     */
    public static final int Utah_VALUE = 49;
    /**
     * <code>Maine = 23;</code>
     */
    public static final int Maine_VALUE = 23;
    /**
     * <code>Vermont = 50;</code>
     */
    public static final int Vermont_VALUE = 50;
    /**
     * <code>Maryland = 24;</code>
     */
    public static final int Maryland_VALUE = 24;
    /**
     * <code>Virgin_Islands = 52;</code>
     */
    public static final int Virgin_Islands_VALUE = 52;
    /**
     * <code>Massachusetts = 25;</code>
     */
    public static final int Massachusetts_VALUE = 25;
    /**
     * <code>Virginia = 51;</code>
     */
    public static final int Virginia_VALUE = 51;
    /**
     * <code>Michigan = 26;</code>
     */
    public static final int Michigan_VALUE = 26;
    /**
     * <code>Washington = 53;</code>
     */
    public static final int Washington_VALUE = 53;
    /**
     * <code>Minnesota = 27;</code>
     */
    public static final int Minnesota_VALUE = 27;
    /**
     * <code>West_Virginia = 54;</code>
     */
    public static final int West_Virginia_VALUE = 54;
    /**
     * <code>Mississippi = 28;</code>
     */
    public static final int Mississippi_VALUE = 28;
    /**
     * <code>Wisconsin = 55;</code>
     */
    public static final int Wisconsin_VALUE = 55;
    /**
     * <code>Missouri = 29;</code>
     */
    public static final int Missouri_VALUE = 29;
    /**
     * <code>Wyoming = 56;</code>
     */
    public static final int Wyoming_VALUE = 56;


    public final int getNumber() { return value; }

    public static STATE valueOf(int value) {
      switch (value) {
        case 1: return Alabama;
        case 30: return Montana;
        case 31: return Nebraska;
        case 2: return Alaska;
        case 32: return Nevada;
        case 4: return Arizona;
        case 33: return New_Hampshire;
        case 5: return Arkansas;
        case 34: return New_Jersey;
        case 6: return California;
        case 35: return New_Mexico;
        case 8: return Colorado;
        case 36: return New_York;
        case 9: return Connecticut;
        case 37: return North_Carolina;
        case 10: return Delaware;
        case 38: return North_Dakota;
        case 11: return District_of_Columbia;
        case 39: return Ohio;
        case 12: return Florida;
        case 40: return Oklahoma;
        case 13: return Georgia;
        case 41: return Oregon;
        case 15: return Hawaii;
        case 42: return Pennsylvania;
        case 16: return Idaho;
        case 43: return Puerto_Rico;
        case 17: return Illinois;
        case 44: return Rhode_Island;
        case 18: return Indiana;
        case 45: return South_Carolina;
        case 19: return Iowa;
        case 46: return South_Dakota;
        case 20: return Kansas;
        case 47: return Tennessee;
        case 21: return Kentucky;
        case 48: return Texas;
        case 22: return Louisiana;
        case 49: return Utah;
        case 23: return Maine;
        case 50: return Vermont;
        case 24: return Maryland;
        case 52: return Virgin_Islands;
        case 25: return Massachusetts;
        case 51: return Virginia;
        case 26: return Michigan;
        case 53: return Washington;
        case 27: return Minnesota;
        case 54: return West_Virginia;
        case 28: return Mississippi;
        case 55: return Wisconsin;
        case 29: return Missouri;
        case 56: return Wyoming;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<STATE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<STATE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<STATE>() {
            public STATE findValueByNumber(int number) {
              return STATE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return boa.types.transportation.State.getDescriptor().getEnumTypes().get(0);
    }

    private static final STATE[] VALUES = values();

    public static STATE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private STATE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:boa.types.transportation.STATE)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013state.proto\022\030boa.types.transportation*" +
      "\230\006\n\005STATE\022\013\n\007Alabama\020\001\022\013\n\007Montana\020\036\022\014\n\010N" +
      "ebraska\020\037\022\n\n\006Alaska\020\002\022\n\n\006Nevada\020 \022\013\n\007Ari" +
      "zona\020\004\022\021\n\rNew_Hampshire\020!\022\014\n\010Arkansas\020\005\022" +
      "\016\n\nNew_Jersey\020\"\022\016\n\nCalifornia\020\006\022\016\n\nNew_M" +
      "exico\020#\022\014\n\010Colorado\020\010\022\014\n\010New_York\020$\022\017\n\013C" +
      "onnecticut\020\t\022\022\n\016North_Carolina\020%\022\014\n\010Dela" +
      "ware\020\n\022\020\n\014North_Dakota\020&\022\030\n\024District_of_" +
      "Columbia\020\013\022\010\n\004Ohio\020\'\022\013\n\007Florida\020\014\022\014\n\010Okl" +
      "ahoma\020(\022\013\n\007Georgia\020\r\022\n\n\006Oregon\020)\022\n\n\006Hawa",
      "ii\020\017\022\020\n\014Pennsylvania\020*\022\t\n\005Idaho\020\020\022\017\n\013Pue" +
      "rto_Rico\020+\022\014\n\010Illinois\020\021\022\020\n\014Rhode_Island" +
      "\020,\022\013\n\007Indiana\020\022\022\022\n\016South_Carolina\020-\022\010\n\004I" +
      "owa\020\023\022\020\n\014South_Dakota\020.\022\n\n\006Kansas\020\024\022\r\n\tT" +
      "ennessee\020/\022\014\n\010Kentucky\020\025\022\t\n\005Texas\0200\022\r\n\tL" +
      "ouisiana\020\026\022\010\n\004Utah\0201\022\t\n\005Maine\020\027\022\013\n\007Vermo" +
      "nt\0202\022\014\n\010Maryland\020\030\022\022\n\016Virgin_Islands\0204\022\021" +
      "\n\rMassachusetts\020\031\022\014\n\010Virginia\0203\022\014\n\010Michi" +
      "gan\020\032\022\016\n\nWashington\0205\022\r\n\tMinnesota\020\033\022\021\n\r" +
      "West_Virginia\0206\022\017\n\013Mississippi\020\034\022\r\n\tWisc",
      "onsin\0207\022\014\n\010Missouri\020\035\022\013\n\007Wyoming\0208"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
